.\" Manpage for myfreerman.

.TH man 1 "myfreerman man page"

.SH NAME

myfreerman \- administer mysql backups

.SH SYNOPSIS

myfreerman [ -c <config> ] [ -l <log file format> ] [ -q ] [ -y ] <command> [ ... ]

myfreerman -h

myfreerman <command> ... -h

.B commands

backup

	full

	binlog

drop-db

init

	database

	slave

list

	full

	binlog

remove

	expired

restore

.SH DESCRIPTION

This is a tool that wraps MySQL Enterprise Backup to handle backups of MySQL databases.

It adds support for:

- Listing full and binlog bakcups

- Compressing binlog backups

- Restoring only a schema / only a list of tables

- Automated PITR

- Recovery window maintenance

- Creating a new database repository

- Creating a new slave server

- Drop a database

.SH CONFIGURATION

The default configuration section is \fBmysqld\fR for the server and \fBmyfreerman\fR for myfreerman. You can define environment variable \fBMYSQL_SID\fR to change the section.
Exemple: MYSQL_SID=dev => sections are mysqld@dev and myfreerman@dev.

.SH OPTIONS

-c Use another configuration file, and not the default /etc/my.cnf.

-l Print output to log file. Variables in format are the same as in "date" command.

-q Quiet mode - do not show release information.

-y Assume YES to all questions.

-h Print help (any command has this option)

.B backup

Backup the database. Used for full backups and for binary log backups.


.B drop-db

Drop current database (data files, binlogs, relay logs, redo and undo).


.B init

Initialize new database, which can be a new master or a slave.


.B list

List current backups.


.B remove

Remove backups.


.B restore

Restore a previously created backup.


.SH SEE ALSO

myfreerman.conf(8)

.SH AUTHOR

Rodrigo Cardoso <rodrigocardoso@tjrs.jus.br>
