.\" Manpage for myfreerman.

.TH man 8 "myfreerman.conf man page"

.SH NAME

myfreerman.conf \- myfreerman configuration

.SH DESCRIPTION

myfreerman reads its configuration from a section in Mysql server's my.cnf configuration file. The default section name is "[myfreerman]". If you need more than one instance in the same host, use "[myfreerman@<sid>]" - where <sid> is Mysql server instance alias, and set MYSQL_SID before calling myfreerman. For example, use "[myfreerman@dev]" and set MYSQL_SID=dev. Configuration variables:

aux_basedir: Directory that the auxiliar instance will use to restore a specific schema/table. Its owner must be mysql.

backup_dir: Directory where backups are going to be saved.

db_password: Database password - optional - mysql_config_editor can be used.

db_username: Database username - optional - mysql_config_editor can be used.

log_dir: log directory. Required when option -l is used.

lock_file: Lock file path. Lock file is used to block simultaneous instances running.

max_mem: max memory Enterprise Backup is allowed to use - in Mb.
   DEFAULT: 300.

read_only: 1 to avoid making backups. Useful for safety when an instance is always only a copy from another one.
   DEFAULT: 0

read_threads: Number of threads for reading tasks.
   DEFAULT: 1.

retention_period: Backup retention period (days).

slave_server: Hostname and port of the slave server that is receiving updates from this master. Format: <host>[:<port>]. Default port is 3306.
   DEFAULT: no slave is configured.

working_file: File where current operation context will be saved. For instance, APPLY BINLOG command needs this file. Cannot be shared between instances on the same server.
   DEFAULT: /var/lib/mysql/myfreerman.work

write_threads: Number of threads for writing tasks.
   DEFAULT: 1.

.SH EXAMPLE

==> Instance: tst

[myfreerman@tst]

aux_basedir=/var/tmp/mysql.aux

backup_dir=/mnt/backup

db_username=root

db_password=passwd1234

log_dir=/var/log/myfreerman

lock_file=/var/lib/myfreerman.lock

retention_period=20

read_threads=5

write_threads=5

.SH SEE ALSO
myfreerman(1)

.SH AUTHOR
Rodrigo Cardoso <rodrigocardoso@tjrs.jus.br>
