#!/bin/bash

function run()
{
	REL=`grep RELEASE= myfreerman | cut -d = -f 2`
	make || return 1
	TAG=v${REL}
	MSG="Version $REL"
	git commit -a -m "$MSG"
	git tag $TAG
	git push || return 1
	git push --tags || return 1
	publish-rpms || return 1
}

run
exit $?
